# Generated by Django 4.2.1 on 2023-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClusterConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(unique=True)),
                (
                    "cloud_provider",
                    models.CharField(
                        choices=[
                            ("aws", "Amazon Web Services"),
                            ("aws-spot", "Spot Amazon Web Services"),
                            ("vultr", "Vultr"),
                        ],
                        max_length=10,
                    ),
                ),
                ("minio_bucket_name", models.TextField()),
            ],
        ),
    ]
