# Generated by Django 4.2.1 on 2023-05-30 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0002_clusterconfiguration_vm_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clusterconfiguration",
            name="vm_username",
        ),
    ]
