# Generated by Django 4.2.1 on 2023-07-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0003_remove_clusterconfiguration_vm_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterconfiguration",
            name="cloud_provider",
            field=models.CharField(
                choices=[("aws", "Amazon Web Services"), ("vultr", "Vultr")],
                max_length=10,
            ),
        ),
    ]
