# Generated by Django 4.2.1 on 2023-08-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0006_clusterconfiguration_entrypoint_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterconfiguration",
            name="efa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clusterconfiguration",
            name="fsx",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clusterconfiguration",
            name="nfs",
            field=models.BooleanField(default=False),
        ),
    ]
