# Generated by Django 4.2.1 on 2023-12-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0007_clusterconfiguration_efa_clusterconfiguration_fsx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterconfiguration",
            name="vcpus",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
