# Generated by Django 4.2.1 on 2023-12-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0009_clusterconfiguration_spawn_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterconfiguration",
            name="instance_type",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
