name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch: # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60 # Set explicit timeout
    strategy:
      matrix:
        include:
          # macOS Intel (x86_64)
          - target: x86_64-apple-darwin
            os: macos-13
            name: macos-intel
            asset_name: hpcac-toolkit-macos-intel
            
          # macOS Apple Silicon (ARM64) - TEMPORARILY SKIPPED
          - target: aarch64-apple-darwin
            os: macos-14
            name: macos-arm64
            asset_name: hpcac-toolkit-macos-arm64
            skip: true
            
          # Linux x86_64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-amd64
            asset_name: hpcac-toolkit-linux-amd64
            
          # Linux ARM64 - TEMPORARILY SKIPPED
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-arm64
            asset_name: hpcac-toolkit-linux-arm64
            use_cross: true
            skip: true

    steps:
      - name: Skip ARM builds temporarily
        if: matrix.skip == true
        run: |
          echo "Skipping ARM build for ${{ matrix.target }}"
          exit 0
          
      - name: Checkout code
        if: matrix.skip != true
        uses: actions/checkout@v4

      - name: Setup Rust
        if: matrix.skip != true
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Rust cache
        if: matrix.skip != true
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
          cache-on-failure: true

      # Create SQLite database for sqlx compile-time checks
      - name: Setup SQLite database
        if: matrix.skip != true
        run: |
          # Install sqlx-cli
          cargo install sqlx-cli --no-default-features --features sqlite
          # Create database and run migrations
          sqlx database create --database-url sqlite://db.sqlite
          sqlx migrate run --database-url sqlite://db.sqlite
        env:
          DATABASE_URL: sqlite://db.sqlite

      # Install cross for Linux ARM64 cross-compilation
      - name: Install cross
        if: matrix.target == 'aarch64-unknown-linux-gnu' && matrix.skip != true
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          # Verify installation
          cross --version

      # Build using cross for Linux ARM64, native for others
      - name: Build binary (cross)
        if: matrix.target == 'aarch64-unknown-linux-gnu' && matrix.skip != true
        run: |
          # Use fewer parallel jobs to reduce memory usage
          cross build --release --target ${{ matrix.target }} --jobs 2
        env:
          CARGO_NET_RETRY: 10
          CARGO_NET_TIMEOUT: 60
          DATABASE_URL: sqlite://db.sqlite

      - name: Build binary (native)
        if: matrix.target != 'aarch64-unknown-linux-gnu' && matrix.skip != true
        run: |
          # For Linux, use static linking to avoid glibc version issues
          if [[ "${{ matrix.target }}" == *"linux"* ]]; then
            export RUSTFLAGS="-C target-feature=+crt-static"
          fi
          cargo build --release --target ${{ matrix.target }} --jobs 2
        env:
          CARGO_NET_RETRY: 10
          CARGO_NET_TIMEOUT: 60
          DATABASE_URL: sqlite://db.sqlite

      # Create the final artifact with proper naming
      - name: Prepare artifact (Unix)
        if: runner.os != 'Windows' && matrix.skip != true
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/hpcac artifacts/${{ matrix.asset_name }}
          chmod +x artifacts/${{ matrix.asset_name }}

      # Create compressed archives
      - name: Create tar.gz (Unix)
        if: runner.os != 'Windows' && matrix.skip != true
        run: |
          cd artifacts
          tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}
          
      # Upload artifacts for the release job
      - name: Upload artifact
        if: matrix.skip != true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: artifacts/${{ matrix.asset_name }}.tar.gz

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            
            - Add your release notes here
            
            ## Downloads
            
            - **macOS Intel**: `hpcac-toolkit-macos-intel.tar.gz`
            - **Linux x86_64**: `hpcac-toolkit-linux-amd64.tar.gz`
            
            *Note: ARM64 builds temporarily disabled*
            
            ## Installation

            1. Download the appropriate archive for your platform
            2. Extract: `tar -xzf hpcac-toolkit-*.tar.gz`
            3. Make executable: `chmod +x hpcac-toolkit-*`
            4. Run: `./hpcac-toolkit-*`
          draft: false
          prerelease: false

      - name: Upload macOS Intel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/hpcac-toolkit-macos-intel/hpcac-toolkit-macos-intel.tar.gz
          asset_name: hpcac-toolkit-macos-intel.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux x86_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/hpcac-toolkit-linux-amd64/hpcac-toolkit-linux-amd64.tar.gz
          asset_name: hpcac-toolkit-linux-amd64.tar.gz
          asset_content_type: application/gzip

      # ARM64 uploads commented out while builds are skipped
      # - name: Upload macOS ARM64
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: artifacts/hpcac-toolkit-macos-arm64/hpcac-toolkit-macos-arm64.tar.gz
      #     asset_name: hpcac-toolkit-macos-arm64.tar.gz
      #     asset_content_type: application/gzip

      # - name: Upload Linux ARM64
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: artifacts/hpcac-toolkit-linux-arm64/hpcac-toolkit-linux-arm64.tar.gz
      #     asset_name: hpcac-toolkit-linux-arm64.tar.gz
      #     asset_content_type: application/gzip
